### ISSUE TITLE
SIGSEGV, Segmentation fault error (a third one) occurs on collisionMoveSimple which may be related to others

### ISSUE THREAD

**Issue by poikilos** [poikilos/EnlivenMinetest#485]
After getting this segfault, #472 (serializing data SEGFAULT) occurs on gathering a tombstone.
```
2021-11-08 11:55:15: ACTION[Server]: singleplayer respawns at (0,9,0)
--Type <RET> for more, q to quit, c to continue without paging--c

Thread 20 "Server" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffac0b5700 (LWP 9168)]
0x00007fffc5000630 in ?? ()
(gdb) where
#0  0x00007fffc5000630 in ?? ()
#1  0x00005555559f5aa5 in collisionMoveSimple (env=0x55555c4ade40, gamedef=0x555556b4a2a8, pos_max_d=pos_max_d@entry=2.5, box_0=..., stepheight=12, 
    dtime=dtime@entry=0.0160000008, pos_f=pos_f@entry=0x7fffac0b453c, speed_f=speed_f@entry=0x7fffac0b4548, accel_f=..., self=0x7fffc4fffbb0, 
    collideWithObjects=true) at /home/owner/linux-minetest-kit-200527/minetest/src/collision.cpp:391
#2  0x0000555555a174c8 in LuaEntitySAO::step (this=0x7fffc4fffbb0, dtime=0.0160000008, send_recommended=<optimized out>)
    at /home/owner/linux-minetest-kit-200527/minetest/src/serverenvironment.h:216
#3  0x0000555555c26dbb in ServerEnvironment::step (this=<optimized out>, dtime=<optimized out>)
    at /home/owner/linux-minetest-kit-200527/minetest/src/serverenvironment.cpp:1421
#4  0x0000555555c05e14 in Server::AsyncRunStep (this=0x555556b4a290, initial_step=<optimized out>)
    at /home/owner/linux-minetest-kit-200527/minetest/src/server.cpp:516
#5  0x0000555555c0911e in ServerThread::run (this=0x555556b5fa60) at /home/owner/linux-minetest-kit-200527/minetest/src/server.cpp:98
#6  0x0000555555927dce in Thread::threadProc (thr=0x555556b5fa60) at /home/owner/linux-minetest-kit-200527/minetest/src/threading/thread.cpp:196
#7  0x00007ffff7753ed0 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007ffff7c30ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#9  0x00007ffff745fdef in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) c
Continuing.
Couldn't get registers: No such process.
Couldn't get registers: No such process.
(gdb) [Thread 0x7fff90bc2700 (LWP 9179) exited]
[Thread 0x7fffa162a700 (LWP 9172) exited]
[Thread 0x7fffaa3b2700 (LWP 9171) exited]
[Thread 0x7fffab0b3700 (LWP 9170) exited]
[Thread 0x7fffab8b4700 (LWP 9169) exited]
[Thread 0x7ffff10fb700 (LWP 9165) exited]
[Thread 0x7fffcb7d8700 (LWP 9164) exited]
[Thread 0x7fffcafd7700 (LWP 9163) exited]
[Thread 0x7fffca7d6700 (LWP 9162) exited]
[Thread 0x7fffc9fd5700 (LWP 9161) exited]
[Thread 0x7ffff332d700 (LWP 7761) exited]
[Thread 0x7ffff3b2e700 (LWP 7760) exited]
[Thread 0x7ffff432f700 (LWP 7759) exited]
[Thread 0x7ffff4b30700 (LWP 7758) exited]
[Thread 0x7ffff612cac0 (LWP 7754) exited]

Program terminated with signal SIGSEGV, Segmentation fault.
```

**Comment by poikilos** [comment]
duplicate of #472
